esphome:
  name: touch-panel
 # platformio_options:
 #   board_build.arduino.memory_type: qio_opi
 #   build_flags:
 #     - -D BOARD_HAS_PSRAM
esp32:
  board: esp32s3box
  framework:
    type: arduino
  #flash_size: 16MB

#psram:
 # mode: octal
 # speed: 80MHz

logger:
  level: DEBUG

api:

web_server:
  port: 80

ota:
  - platform: esphome
    version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

interval:
  - interval: 30s
    then:
      - lambda: |-

light:
  - platform: esp32_rmt_led_strip
    name: "Onboard RGB"
    id: onboard_rgb
    pin: GPIO48
    num_leds: 1
    chipset: WS2812
    rgb_order: GRB
    rmt_channel: 0
    effects:
      - addressable_rainbow: